name: "Practice"

on: [push, pull_request, workflow_dispatch]

env:
  NAME: Kalman

jobs:
  Practice:
    name: Practice
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: echo
      run: echo "Hello ${{ env.NAME}}"